### ISSUE TITLE
Switch to gulp.js for streamlined post processing

### ISSUE THREAD

**Issue by soygul** [soygul/koan#23]

**Comment by BredAnyme** [comment]
i found project with Gulp: http://thejackalofjavascript.com/koa-monk-gulp-getting-started/

**Comment by BredAnyme** [comment]
can at now switch to gulp.js - it has more 4k plugins today

**Comment by soygul** [comment]
It still doesn't have working angular-protractor plugin! I'm revisiting this from time to time but it is still not there.

**Comment by BredAnyme** [comment]
gulp-protractor plugin: https://github.com/mllrsohn/gulp-protractor
and extention of that: https://www.npmjs.com/package/gulp-angular-protractor
i seem that's enough?

**Comment by soygul** [comment]
Yep, seen that last year. Still requires manual download of webdriver along with proper config etc. etc. It's really hard to get it right on all platforms and this dude did put tons of time into it: https://github.com/teerapap/grunt-protractor-runner

this is just one of the things that I'm waiting, there is more.. and I'm on the watch just don't hold your breath yet:)

**Comment by BredAnyme** [comment]
Thank you for your comprehensive answer, I wrote a letter to him to find out plans for the expense Gulp...

**Comment by filso** [comment]
+!

**Comment by soygul** [comment]
I'll revisit this task after angular 2.0 & npm 3.0 are released. I see more and more projects going forward with no task runner. Task runners and custom tasks do no more than wrapping existing tools anyway most the time. We'll see... I like what these guys are doing though: https://github.com/angular/material-start

**Comment by soygul** [comment]
This is now obsoleted by 2.0 branch so closing.
