### ISSUE TITLE
Upgrade to MongoDB 3.0 along with co-mongo/node-mongo when stable versions are out

### ISSUE THREAD

**Issue by soygul** [soygul/koan#49]

**Comment by BredAnyme** [comment]
Hello! i can't find MongoDB 3.0 for ARM6/7 processor - it is good idea else to
add SQLite also support to Koan?

With best regards!

. ..

  05.03.2015, 18:17:37 пользователь Teoman Soygul (notifications@github.com)
  написал:

**Comment by soygul** [comment]
MongoDB 3.0 pretty new. I'm sure that they will release support for other platforms in time.

**Comment by BredAnyme** [comment]
On ARM MongoDB do not any version supported.. but i use Koan on Raspberry Pi for
robot remote interface - i think adding to SQLite support with MongoDB make Koan
most powerfull)

. ..

  08.03.2015, 16:49:15 пользователь Teoman Soygul (notifications@github.com)
  написал:


  MongoDB 3.0 pretty new. I'm sure that they will release support for other
  platforms in time.

**Comment by soygul** [comment]
That is a huge task and I really don't have the time for that. If you are interested, you can fork KOAN repo and start a new project (i.e. Raspberry KOAN) and add sql support and contribute it back to the community.

**Comment by BredAnyme** [comment]
Okey, i add also support SQLite, but before can yours to fork KOAN with Gulp
builder and add me to this repository. I know some plugins of Grunt is never
exist in Gulp - this plugins must to removed. Then, after SQLite adding - i
exending Angular with most popular plugins and make demo interface to rich with
visual effects.

. ..

  08.03.2015, 17:34:17 пользователь Teoman Soygul (notifications@github.com)
  написал:


  That is a huge task and I really don't have the time for that. If you are
  interested, you can fork KOAN repo and start a new project (i.e. Raspberry
  KOAN) and add sql support and contribute it back to the community.

**Comment by soygul** [comment]
Ok, good luck!

**Comment by soygul** [comment]
Closing this as very unrelated discussion polluted the actual issue. Will reopen a new one.
