### ISSUE TITLE
Upgrade to MongoDB 3.0 along with co-mongo/node-mongo when stable versions are out

### ISSUE THREAD

**Issue by soygul** [soygul/koan#50]
node-mongo v3.0 is the target, as v2.0 driver is not 100% tested to be compatible with mongodb 3.0 line.

**Comment by BredAnyme** [comment]
Hello! i tryed to use Koan as service with Forever plugin - but do not working.
If load all modules as global - Koan show error to need local, but plugin Forever
work with global modules. Yours look at this cases?

. ..

  08.03.2015, 18:59:15 пользователь Teoman Soygul (notifications@github.com)
  написал:

**Comment by amit777** [comment]
Awesome project!  I was wondering if you were planning on updating the mongodb dependency.  Just noticed an error when trying to start:

MongoError: driver is incompatible with this server version

**Comment by soygul** [comment]
As soon as node-mongo & co-mongo v3 is out.

**Comment by soygul** [comment]
Done.
