### ISSUE TITLE
WebSocket connection failed

### ISSUE THREAD

**Issue by wychi** [soygul/koan#52]
Hi soygul,

This problem show up recently.

WebSocket connection to 'ws://localhost:3000/?access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImNodWNrQGtvYW4uaGVyb2t1YXBwLmNvbSIsIm5hbWUiOiJDaHVjayBOb3JyaXMiLCJpZCI6MiwicGljdHVyZSI6Ii9hcGkvdXNlcnMvMi9waWN0dXJlIiwiaWF0IjoxNDI3ODIzNDEwLCJleHAiOjE0MzU1OTk0MTB9.2EjG683rHAAK6oexDJw_vzD6m3aDeT5BTrsKgy0Sdo4' failed: HTTP Authentication failed; no valid credentials available

After digging, I found it is caused by koa-jwt update.
koa-jwt@0.1.7 is workable.

I think you might need to specify the version or fix the hack in ws.js
(https://github.com/soygul/koan/blob/master/server/config/ws.js#L29)

**Comment by soygul** [comment]
Good find! Fixated the version to my own fork. It also is the version before critical security issues were introduced so it's good to go now. Thanks for raising the issue.

**Comment by soygul** [comment]
Fixed by a41318b47880148e8724cc1907aeea70d21e047d
