### ISSUE TITLE
Any plans to use Mongoose or some other ODM?

### ISSUE THREAD

**Issue by amit777** [soygul/koan#54]
It would be nice to add business logic to an object representing the entity in Mongo.

**Comment by soygul** [comment]
Nope. Out of the scope of this project as it would be too opinionated.

Also I think that plain node-mongo driver is all you need. As your projects get bigger ODM hinders you more than it helps you.

**Comment by amit777** [comment]
Apologies to re-open.  I'm a bit new to the nodejs environment.  How would you suggest achieving something similar to custom methods on each of the models?  Eg, if I have an animal collection, what way do you to make a custom method like "roar()"

**Comment by soygul** [comment]
Collections in mongo happen to be your data models. You need separate domain models if you like to do domain-driven design. I think GitHub issues is not the right place for DDD discussion. I would suggest Googling around things like `ddd mongodb`.
