### ISSUE TITLE
how deploy nginx proxy

### ISSUE THREAD

**Issue by gatspy** [soygul/koan#80]
i want deploy koan on nginx?  nginx.conf file as follows. but work not correct, in koan ,how add preix `koan`?

```nginx
upstream kapp {
	server 127.0.0.1:60103;
	keepalive 16;
}

location ~* /koan {
	proxy_pass http://kapp;
 }
```

**Comment by soygul** [comment]
I would suggest asking this on stackoverflow. I have no experience with nginx.

**Comment by gatspy** [comment]
@soygul 
Thank you for your reply
